//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContentScriptCreator.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Repos\\sendaiitfes2017\\source\\sessions\\items")]
        public string SessionInfoPath {
            get {
                return ((string)(this["SessionInfoPath"]));
            }
            set {
                this["SessionInfoPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Repos\\sendaiitfes2017\\source\\schedule\\index.html.slim")]
        public string TimetablePath {
            get {
                return ((string)(this["TimetablePath"]));
            }
            set {
                this["TimetablePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Repos\\sendaiitfes2017\\data\\speakers.yml")]
        public string SpeakerYml {
            get {
                return ((string)(this["SpeakerYml"]));
            }
            set {
                this["SpeakerYml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\CommonHeader.html.slim")]
        public string TimeTableCommonHeaderFilename {
            get {
                return ((string)(this["TimeTableCommonHeaderFilename"]));
            }
            set {
                this["TimeTableCommonHeaderFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\TimeTableHeader.html.slim")]
        public string TimeTableHeaderFilename {
            get {
                return ((string)(this["TimeTableHeaderFilename"]));
            }
            set {
                this["TimeTableHeaderFilename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\TimeTableFooter.html.slim")]
        public string TimetableFooterFilePath {
            get {
                return ((string)(this["TimetableFooterFilePath"]));
            }
            set {
                this["TimetableFooterFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsFooterVisible {
            get {
                return ((bool)(this["IsFooterVisible"]));
            }
            set {
                this["IsFooterVisible"] = value;
            }
        }
    }
}
